name: Verify Dockerfile

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        ncs_branch:
          - main
          - v2.4-branch
        include:
          # Defaults
          - ZEPHYR_TOOLCHAIN_VERSION: 0.16.0
            ZEPHYR_TOOLCHAIN_ARCHIVE_FORMAT: xz
            # Removed in v1.9
            asset_tracker: disable
            asset_tracker_v2: enable

          - ncs_branch: v2.4-branch

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build -t nordicplayground/nrfconnect-sdk:${{ matrix.ncs_branch }} \
            --build-arg sdk_nrf_revision=${{ matrix.ncs_branch }} \
            --build-arg ZEPHYR_TOOLCHAIN_VERSION=${{ matrix.ZEPHYR_TOOLCHAIN_VERSION }} \
            --build-arg ZEPHYR_TOOLCHAIN_ARCHIVE_FORMAT=${{ matrix.ZEPHYR_TOOLCHAIN_ARCHIVE_FORMAT }} \
            .

      - name: Build asset_tracker application
        if: matrix.asset_tracker != 'disable'
        run: |
          docker run --rm \
            -v ${PWD}:/workdir/project \
            -w /workdir/nrf/applications/asset_tracker \
            nordicplayground/nrfconnect-sdk:${{ matrix.ncs_branch }} \
              west build -b nrf9160dk_nrf9160ns --build-dir /workdir/project/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"

      - uses: actions/upload-artifact@v3
        if: matrix.asset_tracker != 'disable'
        with:
          if-no-files-found: error
          name: asset_tracker-${{ matrix.ncs_branch }}
          path: |
            build/zephyr/merged.hex
            build/zephyr/app_update.bin

      - name: Build asset_tracker_v2 application
        if: matrix.asset_tracker_v2 != 'disable'
        run: |
          docker run --rm \
            -v ${PWD}:/workdir/project \
            -w /workdir/nrf/applications/asset_tracker_v2 \
            nordicplayground/nrfconnect-sdk:${{ matrix.ncs_branch }} \
              west build -b nrf9160dk_nrf9160ns --build-dir /workdir/project/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"

      - uses: actions/upload-artifact@v3
        if: matrix.asset_tracker_v2 != 'disable'
        with:
          if-no-files-found: error
          name: asset_tracker_v2-${{ matrix.ncs_branch }}
          path: |
            build/zephyr/merged.hex
            build/zephyr/app_update.bin

      - name: Ensure nrfutil works
        run: |
          docker run --rm nordicplayground/nrfconnect-sdk:${{ matrix.ncs_branch }} nrfutil version

      - name: Ensure nrfjprog works
        run: |
          docker run --rm nordicplayground/nrfconnect-sdk:${{ matrix.ncs_branch }} nrfjprog -v

      - name: Ensure clang-format works
        run: |
          docker run --rm nordicplayground/nrfconnect-sdk:${{ matrix.ncs_branch }} clang-format --version
